# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 19:49
from __future__ import unicode_literals

from django.db import migrations
import csv


def movie_data(apps, schema_editor):
    Movie = apps.get_model("movies", "Movie")

    with open("u.item", encoding="latin1") as infile:
        csv_item = csv.reader(infile, delimiter='\t')

    for row in csv_item:
        Movie.objects.create(movie_id="movie id", movie_title="movie title", release_date="release date",
                             video_release_date="video release date", IMDb_URL="IMDB url", unknown="unknown",
                             action="Action", adventure="Adventure", animation="Animation", childrens="Children's",
                             comedy="Comedy", crime="Crime", documentary="Documentary", drama="Drama", fantasy="Fantasy",
                             film_noir="Film-Noir", horror="Horror", musical="Musical", mystery="Mystery",
                             romance="Romance", sci_fi="Sci-Fi", thriller="Thriller", war="War", western="Western")

    raise Exception("Movie yay!")


def rater_data(apps, schema_editor):
    Rater = apps.get_model("movies", "Rater")

    with open("u.user") as infile:
        csv_item = csv.reader(infile, delimiter='\t')

    for row in csv_item:
        Rater.objects.create(user_id="user id", age="age", gender="gender", occupation="occupation", zip_code="zip code")

    raise Exception("Rater yay!")


def rating_data(apps, schema_editor):
    Rating = apps.get_model("movies", "Rating")
    Movie = apps.get_model("movies", "Movie")
    Rater = apps.get_model("movies", "Rater")



    with open("u.data") as infile:
        csv_item = csv.reader(infile, delimiter='\t')

    movie_id = Movie.objects.create([0])
    rater_id = Rater.objects.create([0])

    for row in csv_item:
        Rating.objects.create(user_id="user id", item_id="item id", rating="rating", timestamp="timestamp",
                              movie_id=movie_id, rater_id=rater_id )

    raise Exception("Rating yay!")


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(movie_data), migrations.RunPython(rating_data), migrations.RunPython(rater_data)
    ]
