# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 19:49
from __future__ import unicode_literals

from django.db import migrations
import csv


def create_data(apps, schema_editor):
    Movie = apps.get_model("movies", "Movie")
    Rater = apps.get_model("movies", "Rater")
    Rating = apps.get_model("movies", "Rating")

    with open("u.item", encoding="latin1") as infile:
        csv_file = infile.read()

    csv_file = csv.reader(open(csv_filepathname), delimiter=',', quotechar='"')

    for row in dataReader:
    

    raise Exception("yay")

class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
    ]
