# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 21:44
from __future__ import unicode_literals
from django.db import migrations
from movie_database.worker_function import movie_data
from movie_database.worker_function import rater_data

class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20160607_2142'),
    ]

    operations = [
        migrations.RunPython(movie_data),
        migrations.RunPython(rater_data)
    ]
