# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 17:02
from __future__ import unicode_literals
from django.db import migrations
from movie_database.rating_data import rating_data


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20160607_2144'),
    ]

    operations = [
        migrations.RunPython(rating_data)
    ]
